### PR TITLE
Upstep DO/AS3/TS packages to latest

### PR DESCRIPTION
**Pull request by boeboe**
Upstep of RPM packages to latest available release (30 Mar 2020)

- DO: 1.8.0 => 1.11.1
- AS3: 3.14.0 => 3.18.0
- TS: 1.8.0=> 1.10.0

### CODE REVIEW

**Comment by codygreen** [comment]
@boeboe, do you see customers using the latest version of AS3 versus the LTS version?  I'm okay with the upstep for DO and TS but concerned if the AS3 versions should be LTS.  The customer can always override this on their deployment. thoughts?

@mjmenger please provide input as well.

**Comment by mjmenger** [comment]
I agree that default references to LTS is a better overall pattern. If users wish to use an alternate non-LTS overrides are available.

**Comment by boeboe** [comment]
I checked the documentation on https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html. It states that 3.13 is the latest LTS release, not 3.14. Suggest to add LTS tag on the releases as well to make it visible which one has LTS status.

**Comment by boeboe** [comment]
I will close this issue and move future PR's as branches from the development branch.

**Pull request closed without merging**
